name: run sparrow.py

on:
  schedule:
    - cron: '0 */2 * * *' # At minute 0 past every 2nd hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run sparrow.py
        env:
          open_api_key: ${{ secrets.open_api_key }}
          open_engine: ${{ secrets.open_engine }}
          api_key: ${{ secrets.api_key }}
          api_key_secret: ${{ secrets.api_key_secret }}
          access_token: ${{ secrets.access_token }}
          access_token_secret: ${{ secrets.access_token_secret }}
        run: python sparrow.py
          
      - name: commit files
        run: |
          git config --local user.email "43813358+eldinesh@users.noreply.github.com"
          git config --local user.name "eldinesh"
          git add -A
          git commit -am "chirrup 🐧" --allow-empty
          git push
